# -*- coding: utf-8 -*-
"""cls_ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_9HB1Bvrlqv88adL8_aMoL-tws69tP6a
"""

n1= int(input('Enter the first number:'))
n2 = int(input('Enter the second number:'))

##writefile greaterscript.py 
if n1>n2:
  print('The number',n1,'is greater than',n2) 
else:
  print('The number',n2,'is greater than',n1)

##writefile smallerscript.py
if n1<n2:
  print('The number',n1,'is smaller than',n2) 
else:
  print('The number',n2,'is smaller than',n1)

